### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by Francis0121** [Nornenjs/nornenjs.system#21]
| type | range | var | div |
| --- | --- | --- | --- |
| OTF: | -1 0 1 | -100 0 100 | 100 |
| Scale | 0 1 | 0 100 | 10 |
| Bright | 0 1 2 | 0 100 200 | 100 |

**Comment by uniquerussa** [comment]
rendering type = volume rendering
rotation - O
zoom     - O (이게 좀 더 깊게 들어갈 수 있으면 좋을 것 같음)
Brigtness- 0 (코드 수정하겠음)
OTF      - 0
몸통 -5.0(큐브) ~ 2.0(뼈다구)  볼륨의 크기 512x512x300
머리 -5.0(큐브) ~ 0.5(뼈다구) 볼륨의 크기 256x256x225

rendering type = MIP(엑스레이 영상)
rotation - O
zoom     - O
Brigtness- X
OTF      - X

rendering type = MRI(슬라이스 영상) 
rotation - X
zoom     - X
Brigtness- X
OTF      - X
->  하지만 초기영상의 시점이 바뀌어야 한다.
기본 적으로  시점의 Z위치를 3에서 2로 이동.
X축 방향으로의 영상이 보고싶으면 -> rotationY((기본 각도) - 90, 0, 1, 0)
Y축 방향으로 영상이 보고싶으면 -> rotationY((기본 각도) , 0, 1, 0)
Z축 방향으로 영상이 보고싶으면 -> rotationX((기본 각도) + 90 , 0, 1, 0)
TransferOffset의 초기값은 0
범위는 0~1

**Comment by Francis0121** [comment]
각 모드에 따른 변화만 수행하면됨.
