### ISSUE TITLE
사용자 입력을 통하여 볼륨의 크기입력 받아 출력되게함.

### ISSUE THREAD

**Issue by uniquerussa** [Nornenjs/nornenjs.system#28]
수정 사항1
1.  밝기 조절 기능 완료.
2. 사용자 입력에 따라 볼륨  출력완료.
   복부 데이터도 성공.
   머리 데이터도 성공.

**Comment by uniquerussa** [comment]
두 번째 이슈
1. MRI 영상 출력됨.

하지만 MIP(엑스레이), Volume Rendering(VR)과는 다르게 MRI(슬라이스)영상의 경우 x,y,Z값이 무조건 고정되어있어야한다.
현재 이 x,y,z값이 MIP,VR,MRI 영상에 모두 공유되기 때문에 별도의 처리가 필요할듯.

또한 이와 별개로 MRI 영상에서 transferoffset을 변화 시켜 영상의 변화를 볼 수 있다. 
이 것또한 VR과 변수가 공유되기 때문에 별도의 변수를 만들어야 할듯.

마지막으로 VR의 경우 시점을 정할 때 rotation()의 회전 축방향이 x,y,z축에 따라 다르다.
이 것또한 변수화 시켜서 매번 다르게 만들어 줘야 할듯.

**Comment by Francis0121** [comment]
Question MarkHelpContactJoin
