### ISSUE TITLE
텍스쳐 공유 문제

### ISSUE THREAD

**Issue by Francis0121** [Nornenjs/nornenjs.system#32]
다를 File인데 같은것 공유되서 출력됨

**Comment by uniquerussa** [comment]
생각해 보니 굳이 소스코드를 다시 읽어서 새로 변수명을 바꾸고 그런 작업은 전혀 필요가 없는 작업이라고 생각됨.

왜냐 ptx파일의 이름만 바꿔서 실행하면 결국에는 다른 코드가 되는거지....

즉 사용자가 새로 들어오면
default -> vrcs.cu 이걸 기준으로 해서

vrcs(unique_value).cu 라는 새로운 파일을 만들고 이걸 그냥 컴파일 해서 또다른 ptx를 만들기만 하면되는 것....결국에 사용자마다 다른 코드를 실행하는 건 똑같지.

테스트 결과 정상작동됨. 

즉 우리는 해당 cu파일을 복사해서 코드 변경없이 새로 생성해주기만 하면됨.
로로
방법은 여러가지가 있을 수 있는데 그냥 
1.exec("cp 명령어") -> exec("nvcc 명령어")
2.파일 read해서 다시 write -> exec("nvcc 명령어")

둘중하나 선택해서 하면될듯.

**Comment by uniquerussa** [comment]
nvcc -ptx -o vrcs{value}.ptx vrcs.cu

**Comment by Francis0121** [comment]
그때 도대체 왜 안됬던건진 모르겠으나??

ptx를 새로 생성하지 않아도 잘됨....

**Comment by Francis0121** [comment]
하지만  에러 발생

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by Francis0121** [comment]
ptx 생성하는 코드로 해도 에러 발생

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134
```
